# This workflow is triggered when a GitHub release is created.
# It can also be run manually to re-publish to NPM in case it failed for some reason.
# You can run this workflow by navigating to https://www.github.com/with-ours/platform-sdk-nodejs/actions/workflows/publish-npm.yml
name: Publish NPM
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: production

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24'

      - name: Set up pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Install dependencies
        run: |
          pnpm install

      - name: Publish to NPM
        run: |
          bash ./bin/publish-npm
